"""drop tax_rates

Revision ID: ae3e106053f8
Revises: fe8c28ae62b3
Create Date: 2026-07-15 23:07:14.996406+00:00

Phase 6 (De-Tax-ification). Drops the TaxIQ-era tax_rates table, fully
superseded by police_reference_data since Phase 3 — zero live call sites
referenced it (confirmed by repo-wide grep before this migration was
written).

Autogenerate also detected unrelated drift (timezone-type mismatches and
missing indexes on error_logs/ingestion_jobs/session_attachments — those
tables are created via migrations/003_admin_dashboard_and_attachments.sql's
raw SQL, outside the ORM's purview, so their exact column types/indexes
were never going to match the autogenerated models exactly). That drift
is unrelated to this change and has been hand-trimmed out, same
discipline as every other migration this project has written.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ae3e106053f8'
down_revision: Union[str, None] = 'fe8c28ae62b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('tax_rates')


def downgrade() -> None:
    op.create_table('tax_rates',
    sa.Column('rate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tax_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('filer_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rate_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('fixed_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('effective_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('effective_to', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('section_ref', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_document', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rate_id', name=op.f('tax_rates_pkey'))
    )
