"""
Real generation is wired into every sub-agent that produces prose.

These are wiring tests, not answer-quality tests: they assert that each
sub-agent CALLS the shared generator (rather than returning placeholder text),
that the citation contract survives, and that a generation failure degrades the
way each sub-agent's design says it should.

Answer quality is not assertable here — it needs a live model and real evidence,
which the harness suite deliberately does not have (see conftest).
"""
from __future__ import annotations

import pytest

from src.pipeline.harness import generation
from src.pipeline.harness.contracts import (
    CallerContext,
    ChunkMetadata,
    EvidenceChunk,
    SubAgentInput,
    SubAgentStatus,
)

# Every sub-agent that generates prose, and the generator it must route through.
# report_draft is absent deliberately: it has no generator of its own and reuses
# case_summary's answer_text, so it is covered transitively.
PROSE_AGENTS = [
    ("semantic_search", "generate_case_scoped_answer"),
    ("case_summary", "generate_case_scoped_answer"),
    ("investigative_analysis", "generate_case_scoped_answer"),
    ("timeline", "generate_case_scoped_answer"),
    ("cross_case_linkage", "generate_cross_case_answer"),
    ("aggregate_analysis", "generate_cross_case_answer"),
]


def _agent(name):
    import importlib

    return importlib.import_module(f"src.pipeline.harness.agents.{name}")


@pytest.mark.parametrize("agent_name,generator", PROSE_AGENTS)
def test_sub_agent_imports_the_shared_generator(agent_name, generator):
    """
    Each prose sub-agent binds the shared generator into its own namespace.

    This is what makes the conftest stub effective and, more importantly, what
    guarantees a harness answer is generated by the same code path (and the same
    prompt templates) as the legacy orchestrator's.
    """
    assert hasattr(_agent(agent_name), generator), (
        f"{agent_name} does not import {generator} — it may still be returning "
        f"placeholder prose instead of a generated answer."
    )


@pytest.mark.parametrize("agent_name,_generator", PROSE_AGENTS)
def test_synthesize_is_a_coroutine(agent_name, _generator):
    """
    `_synthesize` must be async: generation is an awaited network call now, and
    a sync stand-in left behind would silently return a coroutine object as the
    answer rather than failing loudly.
    """
    import inspect

    agent = _agent(agent_name)
    if not hasattr(agent, "_synthesize"):
        pytest.skip(f"{agent_name} has no _synthesize")
    assert inspect.iscoroutinefunction(agent._synthesize)


@pytest.mark.asyncio
async def test_generation_failure_abstains_rather_than_serving_prose(monkeypatch):
    """
    A sub-agent whose answer exists only as generated prose must ABSTAIN when
    the generator is unreachable — never serve an unverified draft.
    """
    from src.pipeline.harness.agents import semantic_search

    async def boom(**kwargs):
        raise RuntimeError("model server unreachable")

    monkeypatch.setattr(semantic_search, "generate_case_scoped_answer", boom)

    result = await semantic_search.run(
        SubAgentInput(
            query_text="what happened",
            caller=CallerContext(role="investigator", active_case_id="CASE-1"),
        )
    )

    assert result.status is SubAgentStatus.ABSTAINED
    assert result.answer_text is None
    assert result.citations == []
    # Retrieval succeeded but never reached the user, so RAG is a degradation,
    # not a contributor. [RESOLVED-4]
    assert result.tools_used == []
    assert "RAG" in result.degraded_from
    assert result.error is not None
    assert result.error.kind == "upstream_failure"


@pytest.mark.asyncio
async def test_aggregate_serves_computed_figures_when_generation_fails(monkeypatch):
    """
    XAGG is the deliberate exception: its aggregate is machine-computed and
    correct by construction, so losing the paraphrase must not lose the finding.
    [PRESERVE — design §2.4]
    """
    from src.pipeline.harness.agents import aggregate_analysis

    async def boom(**kwargs):
        raise RuntimeError("model server unreachable")

    monkeypatch.setattr(aggregate_analysis, "generate_cross_case_answer", boom)

    result = await aggregate_analysis.run(
        SubAgentInput(
            query_text="how many cases per category",
            caller=CallerContext(role="supervisor"),
        )
    )

    assert result.status is SubAgentStatus.PARTIAL
    assert result.answer_text, "the computed figures must survive a generator outage"
    assert result.tools_used == ["XAGG"]
    assert any("figures are shown directly" in c for c in result.caveats)


def test_document_numbering_is_positional_and_one_based():
    """
    [PRESERVE — design §5] `[Document N]` must match the chunk's 1-based
    position, because `Citation.document_index` and the Verifier's
    deterministic checks both rely on that correspondence.
    """
    chunks = [
        EvidenceChunk(
            id=f"c{i}",
            text=f"body {i}",
            metadata=ChunkMetadata(source_tool="RAG", source_file=f"f{i}.pdf"),
        )
        for i in range(1, 4)
    ]

    rendered = generation.format_documents_for_prompt(chunks)

    assert "[Document 1] Source: f1.pdf" in rendered
    assert "[Document 2] Source: f2.pdf" in rendered
    assert "[Document 3] Source: f3.pdf" in rendered
    assert "[Document 0]" not in rendered
    assert rendered.index("[Document 1]") < rendered.index("[Document 2]")


def test_low_confidence_links_are_flagged_for_hedging():
    """
    The Verifier's hedging check rejects an unhedged claim resting on a
    low-confidence entity link, so the generator must be TOLD which links are
    low-confidence or it cannot comply.
    """
    low = EvidenceChunk(
        id="c1", text="body",
        metadata=ChunkMetadata(source_tool="XGRAPH", case_id="CASE-1"),
        graph_confidence=0.42,
    )
    high = EvidenceChunk(
        id="c2", text="body",
        metadata=ChunkMetadata(source_tool="XGRAPH", case_id="CASE-2"),
        graph_confidence=0.97,
    )

    rendered = generation.format_documents_for_prompt([low, high])

    assert "must be hedged" in rendered
    assert rendered.count("must be hedged") == 1, "only the low-confidence link"
    assert "[CASE-ID: CASE-1]" in rendered


def test_documents_ride_in_the_user_turn_not_the_system_prompt():
    """
    [PRESERVE — orchestrator.py:1854-1883] Case-file content in the SYSTEM
    prompt triggers the local model's privacy-refusal reflex; the same content
    in the USER turn does not. Confirmed live, and the reason
    `final_response.txt` declares only `{preferred_language}`.
    """
    system_prompt = generation.FINAL_PROMPT_TEMPLATE.format(
        preferred_language="English"
    )
    assert "{documents}" not in generation.FINAL_PROMPT_TEMPLATE
    assert "SECRET_EVIDENCE" not in system_prompt

    user_message = generation.build_case_scoped_user_message(
        query_text="what happened",
        documents_text="[Document 1] SECRET_EVIDENCE",
    )
    assert "SECRET_EVIDENCE" in user_message
    assert "PROVIDED DOCUMENTS" in user_message
    # The untrusted-input boundary is a prompt-injection guard, not boilerplate.
    assert "untrusted" in user_message


def test_urdu_routes_to_the_generation_slot_english_does_not():
    """
    [PRESERVE — orchestrator.py:149-163] Qalb is Urdu-fine-tuned and ignores an
    explicit English instruction, so non-Urdu answers deliberately use the
    reasoning slot. This is not a misconfiguration.
    """
    assert generation.generation_role("Urdu") == "generation"
    assert generation.generation_role("English") == "reasoning"
    assert generation.generation_role(None) == "reasoning"
